### ISSUE TITLE
Mistake in example code

### ISSUE THREAD

**Issue by gemozlobin2** [seregazhuk/learning-amphp#1]
https://github.com/seregazhuk/learning-amphp/blob/1999bd89a99658691498fab1f509ab6f9a7c0232/event-loop/repeat-with-stop.php#L8-L14

This code shows "Hello world" seven times not five times how you wrote in article.
It's because counter starts from 0 and echo operator located before "if". Or you can change cancel condition

**Comment by seregazhuk** [comment]
Good catch, thank you! 👍 
Fixed! I've also fixed snippets and gif in the article.

**Comment by gemozlobin2** [comment]
@seregazhuk 

After fix it will show only four times.

**Comment by seregazhuk** [comment]
@gemozlobin2 why four? On the 5th iteration it cancels the watcher but the code inside `repeat` continues, right?

**Comment by gemozlobin2** [comment]
Yes, I missed that it not immediately break :(
